artifacts:
  blazingSkull: "4"
  wind: "5"
  fruit: "6"
  violin: "7"
  seedBag: "8"
loadout:
  wemwcm: "1"
  damage: "2"
  brew: "3"
menu:
  areas: "v"
  brewing: "d"
  trading: "a"
  leafscend: "f"
trade:
  refresh: "``"
